package com.ssm.mapping;

import com.ssm.dao.UserT;
import com.ssm.dao.UserTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int countByExample(UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int deleteByExample(UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int insert(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int insertSelective(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    List<UserT> selectByExample(UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    UserT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserT record, @Param("example") UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int updateByExample(@Param("record") UserT record, @Param("example") UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int updateByPrimaryKeySelective(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Oct 20 15:35:51 CST 2020
     */
    int updateByPrimaryKey(UserT record);
}